spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deanoffice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
#    connection-timeout: 60000
#    maximum-pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

flyway.baseline-on-migrate: true
#  hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    show_sql: true
#    format_sql: true

server.port: 8080
swagger.host: localhost:8080